Add pipeline for vhd prep

diff --git a/.github/workflows/mshv-infra.yaml b/.github/workflows/mshv-infra.yaml
--- a/.github/workflows/mshv-infra.yaml
+++ b/.github/workflows/mshv-infra.yaml
@@ -6,15 +6,29 @@ on:
         description: 'Architecture for the VM'
         required: true
         type: string
+      OS_DISK_SIZE:
+        description: 'OS Disk Size in GB'
+        required: true
+        type: string
       RG:
         description: 'Resource Group Name'
         required: true
         type: string
-      SKU:
+      SSH_KEY:
+        description: 'SSH Key'
+        required: true
+        type: string
+      VM_SKU:
         description: 'VM SKU'
         required: true
         type: string
     secrets:
+      KEY_VAULT:
+        required: true
+      PRIVATE_KEY:
+        required: true
+      PUBLIC_KEY:
+        required: true
       MI_CLIENT_ID:
         required: true
       RUNNER_RG:
@@ -22,8 +36,6 @@ on:
       RUNNER:
         required: true
       STORAGE_ACCOUNT_PATHS:
-        required: true
-      AARCH64_SOURCE_PATH:
         required: true
       X86_SOURCE_PATH:
         required: true
@@ -34,11 +46,11 @@ on:
         description: 'Private IP of the VM'
         value: ${{ jobs.infra-setup.outputs.PRIVATE_IP }}
 concurrency:
-  group: ${{ github.workflow }}-${{ inputs.ARCH }}-${{ github.ref }}
+  group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
 jobs:
   infra-setup:
-    name: Provision VM for ${{ inputs.ARCH }}
+    name: ${{ inputs.ARCH }} VM Provision
     runs-on: 
       - self-hosted
       - Linux
@@ -80,107 +92,69 @@ jobs:
           az group create --name ${RG} --location ${LOCATION}
           echo "Resource group created successfully."
 
-      - name: Copy/Upload VHD to Azure Storage Account based on architecture
-        env:
-          ARCH: ${{ inputs.ARCH }}
-          IMAGE_NAME: ${{ inputs.ARCH }}-image
-          MI_CLIENT_ID: ${{ secrets.MI_CLIENT_ID }}
-          RG: ${{ inputs.RG }}
-          LOCATION: ${{ env.LOCATION }}
-          SOURCE_PATH_X86: ${{ secrets.X86_SOURCE_PATH }}
-          SOURCE_PATH_AARCH64: ${{ secrets.AARCH64_SOURCE_PATH }}
-          STORAGE_ACCOUNT_PATHS: ${{ secrets.STORAGE_ACCOUNT_PATHS }}
-        run: |
-          set -e
-          echo "Installing AzCopy if not already installed"
-          if ! command -v azcopy &> /dev/null; then
-            wget -O azcopy.tar.gz https://aka.ms/downloadazcopy-v10-linux
-            tar -xvf azcopy.tar.gz
-            sudo mv azcopy*/azcopy /usr/local/bin/
-            sudo chmod +x /usr/local/bin/azcopy
-          fi
-          azcopy --version
-          echo "Logging into AzCopy"
-          azcopy login --identity --identity-client-id ${MI_CLIENT_ID}
-
-          # Retrieve the storage account path
-          STORAGE_ACCOUNT_PATH=$(echo "$STORAGE_ACCOUNT_PATHS" | jq -r 'to_entries[0].value')
-
-          # Determine the source path based on architecture
-          if [ "${ARCH}" == "x86_64" ]; then
-            SOURCE_PATH=${SOURCE_PATH_X86}
-            BLOB_URL="${STORAGE_ACCOUNT_PATH}/${GITHUB_RUN_ID}/x86.vhd"
-          elif [ "${ARCH}" == "aarch64" ]; then
-            SOURCE_PATH=${SOURCE_PATH_AARCH64}
-            BLOB_URL="${STORAGE_ACCOUNT_PATH}/${GITHUB_RUN_ID}/aarch64.vhd"
-          else
-            echo "ERROR: Unsupported architecture: ${ARCH}"
-            exit 1
-          fi
-
-          echo "Uploading VHD to Azure Storage Account"
-          azcopy copy ${SOURCE_PATH} ${BLOB_URL}
-          echo "VHD upload complete"
-
-          # Create Image from the VHD
-          echo "Creating Image"
-          az image create \
-            --resource-group ${RG} \
-            --name ${IMAGE_NAME} \
-            --source $BLOB_URL \
-            --os-type Linux \
-            --location ${LOCATION} \
-            --hyper-v-generation V2 || true
-          echo "Image creation complete"
-
       - name: Generate SSH Key
+        id: generate-ssh-key
+        env:
+          SSH_KEY: ${{ inputs.SSH_KEY }}
         run: |
           # Check if SSH key already exists, if not, generate a new one
-          mkdir -p ~/.ssh
-          if [ ! -f ~/.ssh/azure_key ]; then
-            ssh-keygen -t rsa -b 4096 -f ~/.ssh/azure_key -N ""
-          fi
+          # echo "ssh key: $SSH_KEY"
+          # mkdir -p ~/.ssh
+          # if [ ! -f "${SSH_KEY}" ]; then
+          #   ssh-keygen -t rsa -b 4096 -f "${SSH_KEY}" -N ""
+          # fi
 
       - name: Create VM
         id: vm-setup
         env:
-          IMAGE_NAME: ${{ inputs.ARCH }}-image
+          KEY_VAULT: ${{ secrets.KEY_VAULT }}
+          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
           LOCATION: ${{ env.LOCATION }}
-          OS_DISK_SIZE: 512
+          OS_DISK_SIZE: ${{ inputs.OS_DISK_SIZE }}
           RG: ${{ inputs.RG }}
           RUNNER_RG: ${{ secrets.RUNNER_RG }}
           RUNNER: ${{ secrets.RUNNER }}
-          VM_SKU: ${{ inputs.SKU }}
-          VM_NAME: ${{ inputs.ARCH }}_${{ github.run_id }}
+          SSH_KEY_NAME: ${{ inputs.SSH_KEY_NAME }}
           USERNAME: ${{ secrets.USERNAME }}
+          VM_SKU: ${{ inputs.VM_SKU }}
+          VM_IMAGE_NAME: ${{ inputs.ARCH }}_${{ env.LOCATION }}_image
+          VM_NAME: ${{ inputs.ARCH }}_${{ env.LOCATION }}_${{ github.run_id }}
         run: |
           set -e
-          echo "Starting VM creation process..."
+          echo "Creating $VM_SKU VM: $VM_NAME"
+
           # Extract subnet ID from the runner VM
           echo "Retrieving subnet ID..."
           SUBNET_ID=$(az network vnet list --resource-group ${RUNNER_RG} --query "[?contains(location, '${LOCATION}')].{SUBNETS:subnets}" | jq -r ".[0].SUBNETS[0].id")
-          if [[ -z "$SUBNET_ID" ]]; then
+          if [[ -z "${SUBNET_ID}" ]]; then
             echo "ERROR: Failed to retrieve Subnet ID."
             exit 1
           fi
-          echo "Successfully retrieved Subnet ID: $SUBNET_ID."
+
+          # Extract image ID from the runner VM
+          echo "Retrieving image ID..."
+          IMAGE_ID=$(az image show --resource-group ${RUNNER_RG} --name ${VM_IMAGE_NAME} --query "id" -o tsv)
+          if [[ -z "${IMAGE_ID}" ]]; then
+            echo "ERROR: Failed to retrieve Image ID."
+            exit 1
+          fi
+
+          PUB_KEY=$(az keyvault secret show --name ${PUBLIC_KEY} --vault-name ${KEY_VAULT} --query value -o tsv)
+
           # Create VM
-          echo "Creating VM: $VM_NAME"
-          echo "Using Image: $IMAGE_NAME"
-          echo "Using VM SKU: $VM_SKU"
           az vm create \
             --resource-group ${RG} \
             --name ${VM_NAME} \
-            --subnet $SUBNET_ID \
+            --subnet ${SUBNET_ID} \
             --size ${VM_SKU} \
             --location ${LOCATION} \
-            --image ${IMAGE_NAME} \
+            --image ${IMAGE_ID} \
             --os-disk-size-gb ${OS_DISK_SIZE} \
             --public-ip-sku Standard \
             --storage-sku Premium_LRS \
             --public-ip-address "" \
             --admin-username ${USERNAME} \
-            --ssh-key-value ~/.ssh/azure_key.pub \
+            --ssh-key-value $PUB_KEY \
             --security-type Standard \
             --output json
 
@@ -190,7 +164,7 @@ jobs:
         id: get-vm-ip
         env:
           RG: ${{ inputs.RG }}
-          VM_NAME: ${{ inputs.ARCH }}_${{ github.run_id }}
+          VM_NAME: ${{ inputs.ARCH }}_${{ env.LOCATION }}_${{ github.run_id }}
         run: |
           set -e
           echo "Retrieving VM Private IP address..."
@@ -202,10 +176,15 @@ jobs:
           fi
           echo "PRIVATE_IP=$PRIVATE_IP" >> $GITHUB_OUTPUT
 
-      - name: Wait for SSH availability
-        run: |
-          echo "Waiting for SSH to be accessible..."
-          sleep 30
+      # - name: Wait for SSH availability
+      #   env:
+      #     PRIVATE_IP: ${{ steps.get-vm-ip.outputs.PRIVATE_IP }}
+      #     SSH_KEY: ${{ inputs.SSH_KEY }}
+      #     USERNAME: ${{ secrets.USERNAME }}
+      #   run: |
+      #     echo "Waiting for SSH to be accessible..."
+      #     timeout 120 bash -c 'until ssh -o StrictHostKeyChecking=no -i ${SSH_KEY} ${USERNAME}@${PRIVATE_KEY} "echo VM is up" 2>/dev/null; do sleep 5; done'
+      #     echo "VM is accessible!"
 
       - name: Remove Old Host Key
         env:
@@ -217,12 +196,16 @@ jobs:
 
       - name: SSH into VM and Install Dependencies
         env:
+          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
           PRIVATE_IP: ${{ steps.get-vm-ip.outputs.PRIVATE_IP }}
+          SSH_KEY: ${{ inputs.SSH_KEY }}
           USERNAME: ${{ secrets.USERNAME }}
         run: |
           set -e
-          set +x
-          ssh -i ~/.ssh/azure_key -o StrictHostKeyChecking=no ${USERNAME}@${PRIVATE_IP} << EOF
+          PRIV_KEY=$(az keyvault secret show --name ${PRIVATE_KEY} --vault-name ${KEY_VAULT} --query value -o tsv | sed -E 's/(-----BEGIN [^-]+-----)/\n\1\n/; s/(-----END [^-]+-----)/\n\1\n/' | tr ' ' '\n' | sed '/^$/d')
+          cat private.pem
+          chmod 600 private.pem
+          ssh -i $PRIV_KEY -o StrictHostKeyChecking=no ${USERNAME}@${PRIVATE_IP} << EOF
             set -e
             echo "Logged in successfully."
             echo "Installing dependencies..."
@@ -232,20 +215,5 @@ jobs:
             echo "Installing Rust..."
             curl -sSf https://sh.rustup.rs | sh -s -- --default-toolchain stable --profile default -y
             export PATH="\$HOME/.cargo/bin:\$PATH"
-            cargo --version || { echo "Cargo installation failed"; exit 1; }
-            sudo chown -R ${USERNAME} mshv
-            cd mshv
-
-            # Configure Docker
-            sudo mkdir -p /etc/docker/
-            echo '{"default-ulimits":{"nofile":{"Hard":65535,"Name":"nofile","Soft":65535}}}' | sudo tee /etc/docker/daemon.json
-
-            sudo systemctl stop docker
-            sudo systemctl enable docker.service
-            sudo systemctl enable containerd.service
-            sudo systemctl start docker
-
-            sudo groupadd -f docker
-            sudo usermod -a -G docker ${USERNAME}
-            sudo systemctl restart docker
+            cargo --version
           EOF
